# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b4ca4f8b036909eccfaa4b11476f01af3115cc895bc4d03b491fb29bfd78bab82ab89e72f962964c533deda91a9170c2bcf4f568d8a07e6e11a66c61360b8a2

test:
  secret_key_base: 129cc4c776d11972d2205dcf47258c830b7cd5276244f3b2135302f7d2951ec6e5ab91a3ea1d4731a0c9afc5869ae68546bfc6a3c9b4f3b5bd34d014a691125d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
